version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
