# The docs should build without warnings from sphinx

name: Docs build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  doc-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
      - name: Install docs build dependencies
        run: |
          python -m pip install -rdocs/requirements.txt
          python -m pip install .
      - name: Build docs (fail on warnings)
        run: |
          cd docs
          make clean html SPHINXOPTS="-W --keep-going"
